version: "3.8"

services:
  smart-brain-api:
    container_name: backend
    build: ./
    command: npm start
    working_dir: /usr/src/smart-brain-api
    ports:
      - "3001:3001"
    volumes:
      - ./:/usr/src/smart-brain-api
